//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace mvcForumapp
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class newForumDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new newForumDBEntities object using the connection string found in the 'newForumDBEntities' section of the application configuration file.
        /// </summary>
        public newForumDBEntities() : base("name=newForumDBEntities", "newForumDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new newForumDBEntities object.
        /// </summary>
        public newForumDBEntities(string connectionString) : base(connectionString, "newForumDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new newForumDBEntities object.
        /// </summary>
        public newForumDBEntities(EntityConnection connection) : base(connection, "newForumDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblQuestion> tblQuestions
        {
            get
            {
                if ((_tblQuestions == null))
                {
                    _tblQuestions = base.CreateObjectSet<tblQuestion>("tblQuestions");
                }
                return _tblQuestions;
            }
        }
        private ObjectSet<tblQuestion> _tblQuestions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblReply> tblReplies
        {
            get
            {
                if ((_tblReplies == null))
                {
                    _tblReplies = base.CreateObjectSet<tblReply>("tblReplies");
                }
                return _tblReplies;
            }
        }
        private ObjectSet<tblReply> _tblReplies;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblTechnology> tblTechnologies
        {
            get
            {
                if ((_tblTechnologies == null))
                {
                    _tblTechnologies = base.CreateObjectSet<tblTechnology>("tblTechnologies");
                }
                return _tblTechnologies;
            }
        }
        private ObjectSet<tblTechnology> _tblTechnologies;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblUser> tblUsers
        {
            get
            {
                if ((_tblUsers == null))
                {
                    _tblUsers = base.CreateObjectSet<tblUser>("tblUsers");
                }
                return _tblUsers;
            }
        }
        private ObjectSet<tblUser> _tblUsers;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblQuestions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblQuestions(tblQuestion tblQuestion)
        {
            base.AddObject("tblQuestions", tblQuestion);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblReplies EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblReplies(tblReply tblReply)
        {
            base.AddObject("tblReplies", tblReply);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblTechnologies EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblTechnologies(tblTechnology tblTechnology)
        {
            base.AddObject("tblTechnologies", tblTechnology);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblUsers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblUsers(tblUser tblUser)
        {
            base.AddObject("tblUsers", tblUser);
        }

        #endregion
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<TechResult_Result> TechResult()
        {
            return base.ExecuteFunction<TechResult_Result>("TechResult");
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="techID">No Metadata Documentation available.</param>
        public ObjectResult<QuestionList_Result> QuestionList(Nullable<global::System.Int32> techID)
        {
            ObjectParameter techIDParameter;
            if (techID.HasValue)
            {
                techIDParameter = new ObjectParameter("TechID", techID);
            }
            else
            {
                techIDParameter = new ObjectParameter("TechID", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<QuestionList_Result>("QuestionList", techIDParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="questionID">No Metadata Documentation available.</param>
        public ObjectResult<Questionwithreplys_Result> Questionwithreplys(Nullable<global::System.Int32> questionID)
        {
            ObjectParameter questionIDParameter;
            if (questionID.HasValue)
            {
                questionIDParameter = new ObjectParameter("QuestionID", questionID);
            }
            else
            {
                questionIDParameter = new ObjectParameter("QuestionID", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<Questionwithreplys_Result>("Questionwithreplys", questionIDParameter);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="newForumDBModel", Name="tblQuestion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblQuestion : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblQuestion object.
        /// </summary>
        /// <param name="questionID">Initial value of the QuestionID property.</param>
        /// <param name="questionTitle">Initial value of the QuestionTitle property.</param>
        /// <param name="questionDesc">Initial value of the QuestionDesc property.</param>
        /// <param name="datePosted">Initial value of the DatePosted property.</param>
        /// <param name="userName">Initial value of the UserName property.</param>
        /// <param name="techID">Initial value of the TechID property.</param>
        /// <param name="viewCount">Initial value of the viewCount property.</param>
        /// <param name="replyCount">Initial value of the ReplyCount property.</param>
        public static tblQuestion CreatetblQuestion(global::System.Int32 questionID, global::System.String questionTitle, global::System.String questionDesc, global::System.DateTime datePosted, global::System.String userName, global::System.Int32 techID, global::System.Int32 viewCount, global::System.Int32 replyCount)
        {
            tblQuestion tblQuestion = new tblQuestion();
            tblQuestion.QuestionID = questionID;
            tblQuestion.QuestionTitle = questionTitle;
            tblQuestion.QuestionDesc = questionDesc;
            tblQuestion.DatePosted = datePosted;
            tblQuestion.UserName = userName;
            tblQuestion.TechID = techID;
            tblQuestion.viewCount = viewCount;
            tblQuestion.ReplyCount = replyCount;
            return tblQuestion;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 QuestionID
        {
            get
            {
                return _QuestionID;
            }
            set
            {
                if (_QuestionID != value)
                {
                    OnQuestionIDChanging(value);
                    ReportPropertyChanging("QuestionID");
                    _QuestionID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("QuestionID");
                    OnQuestionIDChanged();
                }
            }
        }
        private global::System.Int32 _QuestionID;
        partial void OnQuestionIDChanging(global::System.Int32 value);
        partial void OnQuestionIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String QuestionTitle
        {
            get
            {
                return _QuestionTitle;
            }
            set
            {
                OnQuestionTitleChanging(value);
                ReportPropertyChanging("QuestionTitle");
                _QuestionTitle = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("QuestionTitle");
                OnQuestionTitleChanged();
            }
        }
        private global::System.String _QuestionTitle;
        partial void OnQuestionTitleChanging(global::System.String value);
        partial void OnQuestionTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String QuestionDesc
        {
            get
            {
                return _QuestionDesc;
            }
            set
            {
                OnQuestionDescChanging(value);
                ReportPropertyChanging("QuestionDesc");
                _QuestionDesc = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("QuestionDesc");
                OnQuestionDescChanged();
            }
        }
        private global::System.String _QuestionDesc;
        partial void OnQuestionDescChanging(global::System.String value);
        partial void OnQuestionDescChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DatePosted
        {
            get
            {
                return _DatePosted;
            }
            set
            {
                OnDatePostedChanging(value);
                ReportPropertyChanging("DatePosted");
                _DatePosted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DatePosted");
                OnDatePostedChanged();
            }
        }
        private global::System.DateTime _DatePosted;
        partial void OnDatePostedChanging(global::System.DateTime value);
        partial void OnDatePostedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TechID
        {
            get
            {
                return _TechID;
            }
            set
            {
                OnTechIDChanging(value);
                ReportPropertyChanging("TechID");
                _TechID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TechID");
                OnTechIDChanged();
            }
        }
        private global::System.Int32 _TechID;
        partial void OnTechIDChanging(global::System.Int32 value);
        partial void OnTechIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 viewCount
        {
            get
            {
                return _viewCount;
            }
            set
            {
                OnviewCountChanging(value);
                ReportPropertyChanging("viewCount");
                _viewCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("viewCount");
                OnviewCountChanged();
            }
        }
        private global::System.Int32 _viewCount;
        partial void OnviewCountChanging(global::System.Int32 value);
        partial void OnviewCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ReplyCount
        {
            get
            {
                return _ReplyCount;
            }
            set
            {
                OnReplyCountChanging(value);
                ReportPropertyChanging("ReplyCount");
                _ReplyCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReplyCount");
                OnReplyCountChanged();
            }
        }
        private global::System.Int32 _ReplyCount;
        partial void OnReplyCountChanging(global::System.Int32 value);
        partial void OnReplyCountChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="newForumDBModel", Name="tblReply")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblReply : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblReply object.
        /// </summary>
        /// <param name="replyID">Initial value of the ReplyID property.</param>
        public static tblReply CreatetblReply(global::System.Int32 replyID)
        {
            tblReply tblReply = new tblReply();
            tblReply.ReplyID = replyID;
            return tblReply;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ReplyID
        {
            get
            {
                return _ReplyID;
            }
            set
            {
                if (_ReplyID != value)
                {
                    OnReplyIDChanging(value);
                    ReportPropertyChanging("ReplyID");
                    _ReplyID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ReplyID");
                    OnReplyIDChanged();
                }
            }
        }
        private global::System.Int32 _ReplyID;
        partial void OnReplyIDChanging(global::System.Int32 value);
        partial void OnReplyIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> QuestionID
        {
            get
            {
                return _QuestionID;
            }
            set
            {
                OnQuestionIDChanging(value);
                ReportPropertyChanging("QuestionID");
                _QuestionID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("QuestionID");
                OnQuestionIDChanged();
            }
        }
        private Nullable<global::System.Int32> _QuestionID;
        partial void OnQuestionIDChanging(Nullable<global::System.Int32> value);
        partial void OnQuestionIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> date
        {
            get
            {
                return _date;
            }
            set
            {
                OndateChanging(value);
                ReportPropertyChanging("date");
                _date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date");
                OndateChanged();
            }
        }
        private Nullable<global::System.DateTime> _date;
        partial void OndateChanging(Nullable<global::System.DateTime> value);
        partial void OndateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TechID
        {
            get
            {
                return _TechID;
            }
            set
            {
                OnTechIDChanging(value);
                ReportPropertyChanging("TechID");
                _TechID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TechID");
                OnTechIDChanged();
            }
        }
        private Nullable<global::System.Int32> _TechID;
        partial void OnTechIDChanging(Nullable<global::System.Int32> value);
        partial void OnTechIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ReplyMsg
        {
            get
            {
                return _ReplyMsg;
            }
            set
            {
                OnReplyMsgChanging(value);
                ReportPropertyChanging("ReplyMsg");
                _ReplyMsg = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ReplyMsg");
                OnReplyMsgChanged();
            }
        }
        private global::System.String _ReplyMsg;
        partial void OnReplyMsgChanging(global::System.String value);
        partial void OnReplyMsgChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="newForumDBModel", Name="tblTechnology")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblTechnology : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblTechnology object.
        /// </summary>
        /// <param name="techID">Initial value of the TechID property.</param>
        /// <param name="techName">Initial value of the TechName property.</param>
        public static tblTechnology CreatetblTechnology(global::System.Int32 techID, global::System.String techName)
        {
            tblTechnology tblTechnology = new tblTechnology();
            tblTechnology.TechID = techID;
            tblTechnology.TechName = techName;
            return tblTechnology;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TechID
        {
            get
            {
                return _TechID;
            }
            set
            {
                if (_TechID != value)
                {
                    OnTechIDChanging(value);
                    ReportPropertyChanging("TechID");
                    _TechID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TechID");
                    OnTechIDChanged();
                }
            }
        }
        private global::System.Int32 _TechID;
        partial void OnTechIDChanging(global::System.Int32 value);
        partial void OnTechIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TechName
        {
            get
            {
                return _TechName;
            }
            set
            {
                OnTechNameChanging(value);
                ReportPropertyChanging("TechName");
                _TechName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TechName");
                OnTechNameChanged();
            }
        }
        private global::System.String _TechName;
        partial void OnTechNameChanging(global::System.String value);
        partial void OnTechNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TechDesc
        {
            get
            {
                return _TechDesc;
            }
            set
            {
                OnTechDescChanging(value);
                ReportPropertyChanging("TechDesc");
                _TechDesc = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TechDesc");
                OnTechDescChanged();
            }
        }
        private global::System.String _TechDesc;
        partial void OnTechDescChanging(global::System.String value);
        partial void OnTechDescChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="newForumDBModel", Name="tblUser")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblUser : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblUser object.
        /// </summary>
        /// <param name="userName">Initial value of the UserName property.</param>
        /// <param name="emailID">Initial value of the EmailID property.</param>
        /// <param name="displayName">Initial value of the DisplayName property.</param>
        /// <param name="dateJoined">Initial value of the DateJoined property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        public static tblUser CreatetblUser(global::System.String userName, global::System.String emailID, global::System.String displayName, global::System.DateTime dateJoined, global::System.String password)
        {
            tblUser tblUser = new tblUser();
            tblUser.UserName = userName;
            tblUser.EmailID = emailID;
            tblUser.DisplayName = displayName;
            tblUser.DateJoined = dateJoined;
            tblUser.Password = password;
            return tblUser;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                if (_UserName != value)
                {
                    OnUserNameChanging(value);
                    ReportPropertyChanging("UserName");
                    _UserName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("UserName");
                    OnUserNameChanged();
                }
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EmailID
        {
            get
            {
                return _EmailID;
            }
            set
            {
                OnEmailIDChanging(value);
                ReportPropertyChanging("EmailID");
                _EmailID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EmailID");
                OnEmailIDChanged();
            }
        }
        private global::System.String _EmailID;
        partial void OnEmailIDChanging(global::System.String value);
        partial void OnEmailIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DisplayName
        {
            get
            {
                return _DisplayName;
            }
            set
            {
                OnDisplayNameChanging(value);
                ReportPropertyChanging("DisplayName");
                _DisplayName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DisplayName");
                OnDisplayNameChanged();
            }
        }
        private global::System.String _DisplayName;
        partial void OnDisplayNameChanging(global::System.String value);
        partial void OnDisplayNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateJoined
        {
            get
            {
                return _DateJoined;
            }
            set
            {
                OnDateJoinedChanging(value);
                ReportPropertyChanging("DateJoined");
                _DateJoined = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateJoined");
                OnDateJoinedChanged();
            }
        }
        private global::System.DateTime _DateJoined;
        partial void OnDateJoinedChanging(global::System.DateTime value);
        partial void OnDateJoinedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Photo
        {
            get
            {
                return StructuralObject.GetValidValue(_Photo);
            }
            set
            {
                OnPhotoChanging(value);
                ReportPropertyChanging("Photo");
                _Photo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Photo");
                OnPhotoChanged();
            }
        }
        private global::System.Byte[] _Photo;
        partial void OnPhotoChanging(global::System.Byte[] value);
        partial void OnPhotoChanged();

        #endregion
    
    }

    #endregion
    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="newForumDBModel", Name="QuestionList_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class QuestionList_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new QuestionList_Result object.
        /// </summary>
        /// <param name="questionID">Initial value of the QuestionID property.</param>
        /// <param name="questionTitle">Initial value of the QuestionTitle property.</param>
        /// <param name="userName">Initial value of the UserName property.</param>
        /// <param name="datePosted">Initial value of the DatePosted property.</param>
        /// <param name="viewCount">Initial value of the viewCount property.</param>
        /// <param name="replyCount">Initial value of the ReplyCount property.</param>
        /// <param name="techID">Initial value of the TechID property.</param>
        /// <param name="techName">Initial value of the TechName property.</param>
        public static QuestionList_Result CreateQuestionList_Result(global::System.Int32 questionID, global::System.String questionTitle, global::System.String userName, global::System.DateTime datePosted, global::System.Int32 viewCount, global::System.Int32 replyCount, global::System.Int32 techID, global::System.String techName)
        {
            QuestionList_Result questionList_Result = new QuestionList_Result();
            questionList_Result.QuestionID = questionID;
            questionList_Result.QuestionTitle = questionTitle;
            questionList_Result.UserName = userName;
            questionList_Result.DatePosted = datePosted;
            questionList_Result.viewCount = viewCount;
            questionList_Result.ReplyCount = replyCount;
            questionList_Result.TechID = techID;
            questionList_Result.TechName = techName;
            return questionList_Result;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 QuestionID
        {
            get
            {
                return _QuestionID;
            }
            set
            {
                OnQuestionIDChanging(value);
                ReportPropertyChanging("QuestionID");
                _QuestionID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("QuestionID");
                OnQuestionIDChanged();
            }
        }
        private global::System.Int32 _QuestionID;
        partial void OnQuestionIDChanging(global::System.Int32 value);
        partial void OnQuestionIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String QuestionTitle
        {
            get
            {
                return _QuestionTitle;
            }
            set
            {
                OnQuestionTitleChanging(value);
                ReportPropertyChanging("QuestionTitle");
                _QuestionTitle = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("QuestionTitle");
                OnQuestionTitleChanged();
            }
        }
        private global::System.String _QuestionTitle;
        partial void OnQuestionTitleChanging(global::System.String value);
        partial void OnQuestionTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DatePosted
        {
            get
            {
                return _DatePosted;
            }
            set
            {
                OnDatePostedChanging(value);
                ReportPropertyChanging("DatePosted");
                _DatePosted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DatePosted");
                OnDatePostedChanged();
            }
        }
        private global::System.DateTime _DatePosted;
        partial void OnDatePostedChanging(global::System.DateTime value);
        partial void OnDatePostedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> date
        {
            get
            {
                return _date;
            }
            set
            {
                OndateChanging(value);
                ReportPropertyChanging("date");
                _date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date");
                OndateChanged();
            }
        }
        private Nullable<global::System.DateTime> _date;
        partial void OndateChanging(Nullable<global::System.DateTime> value);
        partial void OndateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RepliedName
        {
            get
            {
                return _RepliedName;
            }
            set
            {
                OnRepliedNameChanging(value);
                ReportPropertyChanging("RepliedName");
                _RepliedName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RepliedName");
                OnRepliedNameChanged();
            }
        }
        private global::System.String _RepliedName;
        partial void OnRepliedNameChanging(global::System.String value);
        partial void OnRepliedNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 viewCount
        {
            get
            {
                return _viewCount;
            }
            set
            {
                OnviewCountChanging(value);
                ReportPropertyChanging("viewCount");
                _viewCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("viewCount");
                OnviewCountChanged();
            }
        }
        private global::System.Int32 _viewCount;
        partial void OnviewCountChanging(global::System.Int32 value);
        partial void OnviewCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ReplyCount
        {
            get
            {
                return _ReplyCount;
            }
            set
            {
                OnReplyCountChanging(value);
                ReportPropertyChanging("ReplyCount");
                _ReplyCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReplyCount");
                OnReplyCountChanged();
            }
        }
        private global::System.Int32 _ReplyCount;
        partial void OnReplyCountChanging(global::System.Int32 value);
        partial void OnReplyCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ReplyMsg
        {
            get
            {
                return _ReplyMsg;
            }
            set
            {
                OnReplyMsgChanging(value);
                ReportPropertyChanging("ReplyMsg");
                _ReplyMsg = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ReplyMsg");
                OnReplyMsgChanged();
            }
        }
        private global::System.String _ReplyMsg;
        partial void OnReplyMsgChanging(global::System.String value);
        partial void OnReplyMsgChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TechID
        {
            get
            {
                return _TechID;
            }
            set
            {
                OnTechIDChanging(value);
                ReportPropertyChanging("TechID");
                _TechID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TechID");
                OnTechIDChanged();
            }
        }
        private global::System.Int32 _TechID;
        partial void OnTechIDChanging(global::System.Int32 value);
        partial void OnTechIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TechName
        {
            get
            {
                return _TechName;
            }
            set
            {
                OnTechNameChanging(value);
                ReportPropertyChanging("TechName");
                _TechName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TechName");
                OnTechNameChanged();
            }
        }
        private global::System.String _TechName;
        partial void OnTechNameChanging(global::System.String value);
        partial void OnTechNameChanged();

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="newForumDBModel", Name="Questionwithreplys_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class Questionwithreplys_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Questionwithreplys_Result object.
        /// </summary>
        /// <param name="questionID">Initial value of the QuestionID property.</param>
        /// <param name="questionDesc">Initial value of the QuestionDesc property.</param>
        /// <param name="techID">Initial value of the TechID property.</param>
        /// <param name="quesaskedby">Initial value of the quesaskedby property.</param>
        /// <param name="questionTitle">Initial value of the QuestionTitle property.</param>
        /// <param name="datePosted">Initial value of the DatePosted property.</param>
        public static Questionwithreplys_Result CreateQuestionwithreplys_Result(global::System.Int32 questionID, global::System.String questionDesc, global::System.Int32 techID, global::System.String quesaskedby, global::System.String questionTitle, global::System.DateTime datePosted)
        {
            Questionwithreplys_Result questionwithreplys_Result = new Questionwithreplys_Result();
            questionwithreplys_Result.QuestionID = questionID;
            questionwithreplys_Result.QuestionDesc = questionDesc;
            questionwithreplys_Result.TechID = techID;
            questionwithreplys_Result.quesaskedby = quesaskedby;
            questionwithreplys_Result.QuestionTitle = questionTitle;
            questionwithreplys_Result.DatePosted = datePosted;
            return questionwithreplys_Result;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 QuestionID
        {
            get
            {
                return _QuestionID;
            }
            set
            {
                OnQuestionIDChanging(value);
                ReportPropertyChanging("QuestionID");
                _QuestionID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("QuestionID");
                OnQuestionIDChanged();
            }
        }
        private global::System.Int32 _QuestionID;
        partial void OnQuestionIDChanging(global::System.Int32 value);
        partial void OnQuestionIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String QuestionDesc
        {
            get
            {
                return _QuestionDesc;
            }
            set
            {
                OnQuestionDescChanging(value);
                ReportPropertyChanging("QuestionDesc");
                _QuestionDesc = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("QuestionDesc");
                OnQuestionDescChanged();
            }
        }
        private global::System.String _QuestionDesc;
        partial void OnQuestionDescChanging(global::System.String value);
        partial void OnQuestionDescChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TechID
        {
            get
            {
                return _TechID;
            }
            set
            {
                OnTechIDChanging(value);
                ReportPropertyChanging("TechID");
                _TechID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TechID");
                OnTechIDChanged();
            }
        }
        private global::System.Int32 _TechID;
        partial void OnTechIDChanging(global::System.Int32 value);
        partial void OnTechIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String quesaskedby
        {
            get
            {
                return _quesaskedby;
            }
            set
            {
                OnquesaskedbyChanging(value);
                ReportPropertyChanging("quesaskedby");
                _quesaskedby = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("quesaskedby");
                OnquesaskedbyChanged();
            }
        }
        private global::System.String _quesaskedby;
        partial void OnquesaskedbyChanging(global::System.String value);
        partial void OnquesaskedbyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String QuestionTitle
        {
            get
            {
                return _QuestionTitle;
            }
            set
            {
                OnQuestionTitleChanging(value);
                ReportPropertyChanging("QuestionTitle");
                _QuestionTitle = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("QuestionTitle");
                OnQuestionTitleChanged();
            }
        }
        private global::System.String _QuestionTitle;
        partial void OnQuestionTitleChanging(global::System.String value);
        partial void OnQuestionTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DatePosted
        {
            get
            {
                return _DatePosted;
            }
            set
            {
                OnDatePostedChanging(value);
                ReportPropertyChanging("DatePosted");
                _DatePosted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DatePosted");
                OnDatePostedChanged();
            }
        }
        private global::System.DateTime _DatePosted;
        partial void OnDatePostedChanging(global::System.DateTime value);
        partial void OnDatePostedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ReplyID
        {
            get
            {
                return _ReplyID;
            }
            set
            {
                OnReplyIDChanging(value);
                ReportPropertyChanging("ReplyID");
                _ReplyID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReplyID");
                OnReplyIDChanged();
            }
        }
        private Nullable<global::System.Int32> _ReplyID;
        partial void OnReplyIDChanging(Nullable<global::System.Int32> value);
        partial void OnReplyIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> date
        {
            get
            {
                return _date;
            }
            set
            {
                OndateChanging(value);
                ReportPropertyChanging("date");
                _date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date");
                OndateChanged();
            }
        }
        private Nullable<global::System.DateTime> _date;
        partial void OndateChanging(Nullable<global::System.DateTime> value);
        partial void OndateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ReplyMsg
        {
            get
            {
                return _ReplyMsg;
            }
            set
            {
                OnReplyMsgChanging(value);
                ReportPropertyChanging("ReplyMsg");
                _ReplyMsg = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ReplyMsg");
                OnReplyMsgChanged();
            }
        }
        private global::System.String _ReplyMsg;
        partial void OnReplyMsgChanging(global::System.String value);
        partial void OnReplyMsgChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ReplyUser
        {
            get
            {
                return _ReplyUser;
            }
            set
            {
                OnReplyUserChanging(value);
                ReportPropertyChanging("ReplyUser");
                _ReplyUser = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ReplyUser");
                OnReplyUserChanged();
            }
        }
        private global::System.String _ReplyUser;
        partial void OnReplyUserChanging(global::System.String value);
        partial void OnReplyUserChanged();

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="newForumDBModel", Name="TechResult_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class TechResult_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TechResult_Result object.
        /// </summary>
        /// <param name="techName">Initial value of the TechName property.</param>
        /// <param name="technID">Initial value of the TechnID property.</param>
        public static TechResult_Result CreateTechResult_Result(global::System.String techName, global::System.Int32 technID)
        {
            TechResult_Result techResult_Result = new TechResult_Result();
            techResult_Result.TechName = techName;
            techResult_Result.TechnID = technID;
            return techResult_Result;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TechID
        {
            get
            {
                return _TechID;
            }
            set
            {
                OnTechIDChanging(value);
                ReportPropertyChanging("TechID");
                _TechID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TechID");
                OnTechIDChanged();
            }
        }
        private Nullable<global::System.Int32> _TechID;
        partial void OnTechIDChanging(Nullable<global::System.Int32> value);
        partial void OnTechIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> QuestionID
        {
            get
            {
                return _QuestionID;
            }
            set
            {
                OnQuestionIDChanging(value);
                ReportPropertyChanging("QuestionID");
                _QuestionID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("QuestionID");
                OnQuestionIDChanged();
            }
        }
        private Nullable<global::System.Int32> _QuestionID;
        partial void OnQuestionIDChanging(Nullable<global::System.Int32> value);
        partial void OnQuestionIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String QuestionTitle
        {
            get
            {
                return _QuestionTitle;
            }
            set
            {
                OnQuestionTitleChanging(value);
                ReportPropertyChanging("QuestionTitle");
                _QuestionTitle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("QuestionTitle");
                OnQuestionTitleChanged();
            }
        }
        private global::System.String _QuestionTitle;
        partial void OnQuestionTitleChanging(global::System.String value);
        partial void OnQuestionTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DatePosted
        {
            get
            {
                return _DatePosted;
            }
            set
            {
                OnDatePostedChanging(value);
                ReportPropertyChanging("DatePosted");
                _DatePosted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DatePosted");
                OnDatePostedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DatePosted;
        partial void OnDatePostedChanging(Nullable<global::System.DateTime> value);
        partial void OnDatePostedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                OnUsernameChanging(value);
                ReportPropertyChanging("Username");
                _Username = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Username");
                OnUsernameChanged();
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TechName
        {
            get
            {
                return _TechName;
            }
            set
            {
                OnTechNameChanging(value);
                ReportPropertyChanging("TechName");
                _TechName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TechName");
                OnTechNameChanged();
            }
        }
        private global::System.String _TechName;
        partial void OnTechNameChanging(global::System.String value);
        partial void OnTechNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TechDesc
        {
            get
            {
                return _TechDesc;
            }
            set
            {
                OnTechDescChanging(value);
                ReportPropertyChanging("TechDesc");
                _TechDesc = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TechDesc");
                OnTechDescChanged();
            }
        }
        private global::System.String _TechDesc;
        partial void OnTechDescChanging(global::System.String value);
        partial void OnTechDescChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TechnID
        {
            get
            {
                return _TechnID;
            }
            set
            {
                OnTechnIDChanging(value);
                ReportPropertyChanging("TechnID");
                _TechnID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TechnID");
                OnTechnIDChanged();
            }
        }
        private global::System.Int32 _TechnID;
        partial void OnTechnIDChanging(global::System.Int32 value);
        partial void OnTechnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Totalposts
        {
            get
            {
                return _Totalposts;
            }
            set
            {
                OnTotalpostsChanging(value);
                ReportPropertyChanging("Totalposts");
                _Totalposts = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Totalposts");
                OnTotalpostsChanged();
            }
        }
        private Nullable<global::System.Int32> _Totalposts;
        partial void OnTotalpostsChanging(Nullable<global::System.Int32> value);
        partial void OnTotalpostsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ReplyCount
        {
            get
            {
                return _ReplyCount;
            }
            set
            {
                OnReplyCountChanging(value);
                ReportPropertyChanging("ReplyCount");
                _ReplyCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReplyCount");
                OnReplyCountChanged();
            }
        }
        private Nullable<global::System.Int32> _ReplyCount;
        partial void OnReplyCountChanging(Nullable<global::System.Int32> value);
        partial void OnReplyCountChanged();

        #endregion
    }

    #endregion
    
}
